In [20]:
import sys
sys.path.append('/media/data/hungnt/work/Datasets/BTMD/Code/src')

import os
import config
import utils
import sklearn
import numpy as np

from utils import make_ndarray_from_csv, get_int_label
from sklearn.ensemble import RandomForestClassifier

In [21]:
fold = '1.5'
train_features, train_labels = make_ndarray_from_csv(fold, mode = 'train')
test_features, test_labels = make_ndarray_from_csv(fold, mode = 'test')
train_features.shape, train_labels.shape, test_features.shape, test_labels.shape

((1796, 10000), (1796,), (408, 10000), (408,))

In [22]:
train_labels_int = np.array([get_int_label(label) for label in train_labels])
test_labels_int = np.array([get_int_label(label) for label in test_labels])

In [23]:
clf = RandomForestClassifier(max_depth = None, criterion = 'log_loss', oob_score= True, random_state = 42, verbose=1)
his = clf.fit(train_features, train_labels_int)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:   24.4s finished


In [24]:
his.n_features_in_, his.n_classes_, his.classes_

(10000, 14, array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]))

In [25]:
his.feature_importances_, his.feature_importances_.shape, his.n_outputs_

(array([0.00000000e+00, 3.17754855e-04, 4.39250786e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]),
 (10000,),
 1)

In [26]:
his.oob_score_

0.9732739420935412

In [27]:
rand = np.random.randint(low=0, high=10000, size=(1, 10000))
print(rand.shape)
print(rand)

(1, 10000)
[[2012 2524 6088 ... 1485 5495 6305]]


In [28]:
his.predict(rand)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished


array([1])

In [29]:
print(test_features[0], test_labels[0])

[0.98690354 0.         1.         ... 0.58656927 0.88583208 0.13289737] Glioblastoma


In [30]:
clf.score(test_features, test_labels_int)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished


0.9852941176470589

Ở đây do các features trong mỗi fold là khác nhau nên không thể sử dụng model của fold này để test trên fold khác được. Ví dụ dưới đây sẽ cho kết quả rất thấp

In [31]:
test_fold = '1.0'
test_test_features, test_test_labels = make_ndarray_from_csv(test_fold, mode = 'test')
test_test_labels_int = np.array([get_int_label(label) for label in test_test_labels])

In [32]:
test_test_features.shape, test_test_labels_int.shape

((597, 10000), (597,))

In [33]:
clf.score(test_test_features, test_test_labels_int)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished


0.16917922948073702

In [34]:
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'log_loss',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': True,
 'random_state': 42,
 'verbose': 1,
 'warm_start': False}

In [35]:
clf

RandomForestClassifier(criterion='log_loss', oob_score=True, random_state=42,
                       verbose=1)

In [36]:
rand_apply = clf.apply(rand)
rand_apply, rand_apply.shape

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished


(array([[258, 260, 272, 270, 240, 248, 228, 264, 230, 262, 252, 248, 238,
         266, 240, 264, 280, 258, 248, 240, 250, 224, 244, 232, 238, 240,
         258, 226, 272, 282, 256, 280, 264, 242, 256, 250, 236, 246, 260,
         274, 262, 228, 248, 284, 234, 250, 274, 242, 266, 258, 256, 278,
         250, 268, 234, 230, 252, 230, 238, 256, 244, 222, 234, 230, 260,
         272, 212, 238, 250, 256, 236, 254, 246, 234, 262, 236, 260, 256,
         248, 256, 250, 242, 256, 246, 260, 262, 244, 230, 234, 260, 268,
         244, 250, 240, 218, 246, 248, 214, 238, 266]]),
 (1, 100))

In [37]:
decision_path = clf.decision_path(rand)
decision_path, decision_path[1].shape, decision_path[0].shape

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished


((<1x25056 sparse matrix of type '<class 'numpy.int64'>'
  	with 709 stored elements in Compressed Sparse Row format>,
  array([    0,   259,   520,   793,  1064,  1305,  1554,  1783,  2048,
          2279,  2542,  2795,  3044,  3283,  3550,  3791,  4056,  4337,
          4596,  4845,  5086,  5337,  5562,  5807,  6040,  6279,  6520,
          6779,  7006,  7279,  7562,  7819,  8100,  8365,  8608,  8865,
          9116,  9353,  9600,  9861, 10136, 10399, 10628, 10877, 11162,
         11397, 11648, 11923, 12166, 12433, 12692, 12949, 13228, 13479,
         13748, 13983, 14214, 14467, 14698, 14937, 15194, 15439, 15662,
         15897, 16128, 16389, 16662, 16875, 17114, 17365, 17622, 17859,
         18114, 18361, 18596, 18859, 19096, 19357, 19614, 19863, 20120,
         20371, 20614, 20871, 21118, 21379, 21642, 21887, 22118, 22353,
         22614, 22883, 23128, 23379, 23620, 23839, 24086, 24335, 24550,
         24789, 25056])),
 (101,),
 (1, 25056))